---
- name: Converge
  hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
    - name: "Include ansible-role-ustreamer"
      include_role:
        name: "ansible-role-ustreamer"
      vars:
        # Test on 4.13, as v5 seems to require a different gcc version.
        ustreamer_repo_version: "v4.13"
